apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "resource-limits"
spec:
  limits:
    -
      type: "Pod"
      max:
        cpu: "4"
        memory: "4Gi"
      min:
        cpu: "200m"
        memory: "6Mi"
    -
      type: "Container"
      max:
        cpu: "4"
        memory: "4Gi"
      min:
        cpu: "200m"
        memory: "6Mi"
      default:
        cpu: "4"
        memory: "4Gi"
      defaultRequest:
        cpu: "1"
        memory: "512Mi"
