apiVersion: "v1"
kind: "LimitRange"
metadata:
  name: "core-resource-limits"
spec:
  limits:
    - type: "Pod"
      max:
        cpu: "12"
        memory: "12Gi"
      min:
        cpu: "200m"
        memory: "6Mi"
    - type: "Container"
      max:
        cpu: "6"
        memory: "8Gi"
      min:
        cpu: "100m"
        memory: "4Mi"
      default:
        cpu: "4"
        memory: "4Gi"
      defaultRequest:
        cpu: "2"
        memory: "1Gi"
      maxLimitRequestRatio:
        cpu: "2"
    - type: openshift.io/Image
      max:
        storage: 1Gi
    - type: openshift.io/ImageStream
      max:
        openshift.io/image-tags: 30
        openshift.io/images: 40
