
- name: Updating DNS1 in ifcfg-ens192
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens192
    state: present
    regexp: '^DNS1='
    line: 'DNS1=168.94.89.251'
  notify: restart network

- name: Updating DNS2 in ifcfg-ens192
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-ens192
    state: present
    regexp: '^DNS2='
    line: 'DNS2=168.94.169.251'
  notify: restart network
