kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: '{{ name | mandatory }}'
spec:
  accessModes:
    - '{{ mode | mandatory | default(ReadWriteOnce) }}'
  resources:
    requests:
      storage: '{{ size | mandatory }}'
  volumeName: '{{ name | mandatory }}'
