apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgressql
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /ocp_esp_foundation_build_postgressql
    server: 172.21.235.254
  persistentVolumeReclaimPolicy: Recycle
