apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper1
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /ocp_esp_caecomm_test_zookeeper1
    server: 172.21.235.253
  persistentVolumeReclaimPolicy: Recycle
