apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  name: logging-es-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 240Gi
  volumeName: logging-vol
status: {}
