apiVersion: v1
kind: PersistentVolume
metadata:
  name: artifactory
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /ocp_esp_caecomm_build_artifactory
    server: 172.21.235.253
  persistentVolumeReclaimPolicy: Recycle
