apiVersion: v1
kind: PersistentVolume
metadata:
  name: esp-foundation-artifactory
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /ocp_esp_foundation_build_artifactory
    server: 172.21.235.254
  persistentVolumeReclaimPolicy: Recycle
