apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  name: logging-vol
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 240Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: logging-es-0
    namespace: logging
    resourceVersion: "12168896"
    uid: 1e3d78af-263a-11e8-90b2-0050568946cb
  iscsi:
    fsType: ext4
    iqn: iqn.1992-08.com.netapp:sn.e79f223ce99111e6b94e00a098c35956:vs.5
    iscsiInterface: default
    lun: 1
    portals:
    - 168.94.63.89:3260
    - 168.94.63.90:3260
    - 168.94.63.91:3260
    - 168.94.63.92:3260
    targetPortal: 168.94.63.89:3260
  persistentVolumeReclaimPolicy: Retain
status: {}
