apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  name: registry-storage-1
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 300Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: registry-storage-1
    namespace: default
    resourceVersion: "1036595"
    uid: a9f8836b-0543-11e8-b381-00505689402e
  nfs:
    path: /openshift_canada_prod/infra_docker_001
    server: hnacorp01sl
  persistentVolumeReclaimPolicy: Recycle
status: {}
