apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins
spec:
  capacity:
    storage: 32Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /ocp_esp_caecomm_build_jenkins
    server: 172.21.235.253
  persistentVolumeReclaimPolicy: Recycle
