apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: null
  name: metrics-cassandra-2
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 120Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: metrics-cassandra-1
    namespace: openshift-infra
    resourceVersion: "198898282"
    uid: e42123cc-a256-11e8-84d0-005056896431
  iscsi:
    iqn: iqn.1992-08.com.netapp:sn.e2d1c013efc011e681e800a098ad3a7a:vs.5
    iscsiInterface: default
    lun: 0
    portals:
    - 172.16.72.185:3260
    - 172.16.72.186:3260
    - 172.16.72.187:3260
    - 172.16.72.188:3260
    targetPortal: 172.16.72.185:3260
  persistentVolumeReclaimPolicy: Retain
status: {}
