apiVersion: v1
kind: PersistentVolume
metadata:
  name: metrics-cassandra
spec:
  capacity:
    storage: 100Gi
  accessModes:
  - ReadWriteOnce
  iscsi:
    targetPortal: 168.94.63.89:3260
    portals: ['168.94.63.89:3260', '168.94.63.90:3260', '168.94.63.91:3260', '168.94.63.92:3260']
    iqn: iqn.1992-08.com.netapp:sn.e79f223ce99111e6b94e00a098c35956:vs.5
    lun: 0
    fsType: ext4
    readOnly: false
