apiVersion: v1
kind: PersistentVolume
metadata:
  name: ocp-dev-corp-tms-appt-scheduler-dev-new
spec:
  capacity:
    storage: 9Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /ocp_dev_corp_mcl_delivery_engine
    server: 172.21.235.253
  persistentVolumeReclaimPolicy: Retain
