apiVersion: v1
kind: PersistentVolume
metadata:
  name: logging-vol
spec:
  capacity:
    storage: 295Gi 
  accessModes:
  - ReadWriteOnce
  nfs: 
    path: /ocp_logging
    server: 172.21.135.251 
  persistentVolumeReclaimPolicy: Recycle
