kind: LDAPSyncConfig
apiVersion: v1
bindDN: cn=BCA-S-OSHIFT-DEV-AD,ou=Infrastructure,ou=Service Accounts,ou=ECOMM,dc=ca,dc=bestbuy,dc=com
bindPassword: C5V5rR2cjxuMns2XMgSHXvKDLV2QmE
url: ldap://ad-ca.ca.bestbuy.com
insecure: true
ca: ''
augmentedActiveDirectory:
    groupsQuery:
        baseDN: "OU=OPENSHIFT,OU=Groups,OU=ECOMM,DC=ca,DC=bestbuy,DC=com"
        scope: sub
        derefAliases: always
        pageSize: 0
        timeout: 0
    groupUIDAttribute: dn
    groupNameAttributes: [ cn ]
    usersQuery:
        baseDN: "ou=Users,ou=Best Buy Canada,dc=ca,dc=bestbuy,dc=com"
        scope: sub
        derefAliases: never
        pageSize: 0
        filter: (objectclass=*)
    userNameAttributes: [ sAMAccountName ]
    groupMembershipAttributes: [ "memberof:1.2.840.113556.1.4.1941:" ]
