apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: egress-retail-pil
spec:
  ports:
  - name: oracle
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: egress-retail-pil
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
