#Use this sysdig.yaml when Daemon Sets are enabled on Kubernetes (minimum version 1.1.1). Otherwise use the RC method.

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: sysdig-agent
  labels:
    app: sysdig-agent
spec:
  template:
    metadata:
      labels:
        name: sysdig-agent
    spec:
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
      - name: docker-sock
        hostPath:
         path: /var/run/docker.sock
      - name: dev-vol
        hostPath:
         path: /dev
      - name: proc-vol
        hostPath:
         path: /proc
      - name: boot-vol
        hostPath:
         path: /boot
      - name: modules-vol
        hostPath:
         path: /lib/modules
      - name: usr-vol
        hostPath:
          path: /usr
      hostNetwork: true
      hostPID: true
      serviceAccount: sysdig-agent                         #OPTIONAL - OpenShift service account for OpenShift
      nodeSelector:
        sysdig: "true"
      containers:
      - name: sysdig-agent
        image: registry.prod-ocp.ca.xxxxxx.com/sysdig-cloud/agent:latest
#        imagePullPolicy: Always                            #OPTIONAL - Always pull the latest container image tag
        securityContext:
         privileged: true
        env:
        - name: ACCESS_KEY                                  #REQUIRED - replace with your Sysdig Cloud access key
          value: 119c81a1-93cf-4fee-ab58-c8bd639ebd1c
#        - name: RUN_MODE                                   #OPTIONAL - driverless mode (limited functionality. No kernel module. Minimum agent version 0.51.0)
#          value: "nodriver"
        - name: COLLECTOR_PORT                             #OPTIONAL - on-prem install only
          value: "6443"
        - name: TAGS                                       #OPTIONAL
          value: orchestrator:openshift-ca-prod,role:node
        - name: COLLECTOR                                  #OPTIONAL - on-prem install only
          value: 172.21.76.41
        - name: SECURE                                     #OPTIONAL - on-prem install only
          value: "true"
        - name: CHECK_CERTIFICATE                          #OPTIONAL - on-prem install only
          value: "false"
        - name: ADDITIONAL_CONF                            #OPTIONAL pass additional parameters to the agent such as authentication example provided here
          value: 'k8s_delegated_nodes: 12\njmx:\n  limit: 4000\njmx:\n  per_process_beans:\n    FraudService:\n      pattern: order-fraud-service\n      beans:\n        - query: com.netflix.servo:name=countSuccess,*\n          attributes:\n            - name: value\n              alias: hystrix.{instance}.countSuccess\n              type: counter\n        - query: com.netflix.servo:name=countFailure,*\n          attributes:\n            - name: value\n              alias: hystrix.{instance}.countFailure\n              type: counter\n        - query: com.netflix.servo:name=errorPercentage,*\n          attributes:\n            - name: value\n              alias: hystrix.{instance}.errorPercentage\n              type: counter\n        - query: com.netflix.servo:name=latencyExecute_mean,*\n          attributes:\n            - name: value\n              alias: hystrix.{instance}.latencyExecute_mean\n              type: counter\n        - query: com.netflix.servo:name=latencyTotal_mean,*\n          attributes:\n            - name: value\n              alias: hystrix.{instance}.latencyTotal_mean\n              type: counter\n        - query: com.netflix.servo:name=rollingCountFailure,*\n          attributes:\n            - name: value\n              alias: hystrix.{instance}.rollingCountFailure\n              type: counter\n        - query: com.netflix.servo:name= rollingCountSuccess,*\n          attributes:\n            - name: value\n              alias: hystrix.{instance}.rollingCountSuccess\n              type: counter'
        volumeMounts:
        - mountPath: /host/var/run/docker.sock
          name: docker-sock
          readOnly: false
        - mountPath: /host/dev
          name: dev-vol
          readOnly: false
        - mountPath: /host/proc
          name: proc-vol
          readOnly: true
        - mountPath: /host/boot
          name: boot-vol
          readOnly: true
        - mountPath: /host/lib/modules
          name: modules-vol
          readOnly: true
        - mountPath: /host/usr
          name: usr-vol
          readOnly: true
        - mountPath: /dev/shm
          name: dshm
