---
- hosts: uservm
  become: true

  tasks:
  - name: Create a storage directory under /opt
    file: path=/opt/archive state=directory mode=0755

  - name: pull docker images
    docker_image:
      name: "{{ item }}"
    with_items:
      - registry.prod-ocp.na.bestbuy.com/openshift3/ose-haproxy-router:v3.7.42
      - registry.prod-ocp.na.bestbuy.com/openshift3/ose-pod:latest
      - registry.prod-ocp.na.bestbuy.com/openshift3/ose-deployer:v3.7.42
    tags:
    - docker

  - name: Archive image ose3-images.tar
    docker_image:
      name: "{{ item }}"
      tag: v1
      archive_path: /opt/archive/ose3-images.tar
      timeout: 300
    with_items:
      - registry.access.redhat.com/openshift3/ose-ansible:latest
      - registry.access.redhat.com/openshift3/ose-cluster-capacity:latest
      - registry.access.redhat.com/openshift3/ose-deployer:latest
      - registry.access.redhat.com/openshift3/ose-docker-builder:latest
      - registry.access.redhat.com/openshift3/ose-docker-registry:latest
      - registry.access.redhat.com/openshift3/ose-egress-http-proxy:latest
      - registry.access.redhat.com/openshift3/ose-egress-router:latest
      - registry.access.redhat.com/openshift3/ose-f5-router:latest
      - registry.access.redhat.com/openshift3/ose-federation:latest
      - registry.access.redhat.com/openshift3/ose-haproxy-router:latest
      - registry.access.redhat.com/openshift3/ose-keepalived-ipfailover:latest
      - registry.access.redhat.com/openshift3/ose-pod:latest
      - registry.access.redhat.com/openshift3/ose-sti-builder:latest
      - registry.access.redhat.com/openshift3/ose:latest
      - registry.access.redhat.com/openshift3/container-engine:latest
      - registry.access.redhat.com/openshift3/efs-provisioner:latest
      - registry.access.redhat.com/openshift3/node:latest
      - registry.access.redhat.com/openshift3/openvswitch:latest

  - name: Archive image ose3-logging-metrics-images.tar
    docker_image:
      name: "{{ item }}"
      tag: v1
      archive_path: /opt/archive/ose3-logging-metrics-images.tar
      timeout: 300
    with_items:
      - registry.access.redhat.com/openshift3/logging-auth-proxy:latest
      - registry.access.redhat.com/openshift3/logging-curator:latest
      - registry.access.redhat.com/openshift3/logging-deployer:latest
      - registry.access.redhat.com/openshift3/logging-elasticsearch:latest
      - registry.access.redhat.com/openshift3/logging-fluentd:latest
      - registry.access.redhat.com/openshift3/logging-kibana:latest
      - registry.access.redhat.com/openshift3/metrics-cassandra:latest
      - registry.access.redhat.com/openshift3/metrics-deployer:latest
      - registry.access.redhat.com/openshift3/metrics-hawkular-metrics:latest
      - registry.access.redhat.com/openshift3/metrics-hawkular-openshift-agent:latest
      - registry.access.redhat.com/openshift3/metrics-heapster:latest

  - name: Archive image ose3-builder-images.tar
    docker_image:
      name: "{{ item }}"
      tag: v1
      archive_path: /opt/archive/ose3-builder-images.tar
      timeout: 300
    with_items:
      - registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift:latest
      - registry.access.redhat.com/jboss-webserver-3/webserver30-tomcat7-openshift:1.1
      - registry.access.redhat.com/openshift3/jenkins-1-rhel7:latest
      - registry.access.redhat.com/openshift3/jenkins-2-rhel7:latest
      - registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7:latest
      - registry.access.redhat.com/openshift3/jenkins-slave-maven-rhel7:latest
      - registry.access.redhat.com/openshift3/jenkins-slave-nodejs-rhel7:latest
