---
- hosts: nodes
  serial: 1

  tasks:
  - name: Reboot server
    command: /usr/bin/systemd-run --on-active=5 /usr/bin/systemctl reboot
    async: 0
    poll: 0

  - name: Wait for server to be online
    local_action:
      wait_for
        host={{ inventory_hostname }}
        port=22
        delay=60
        timeout=300
