---
- hosts: nodes
  vars:
    kernelversion: 3.10.0-957.1.3.el7.x86_64

  tasks:
  - name: Upgrade all packages
    yum:
      name: '*'
      state: latest
      update_cache: yes
      exclude: ansible-*, docker*1.20*, docker*1.19*, docker*1.18*, docker*1.17*, docker*1.16*, docker*1.15*, docker*1.14*, docker*1.13*, kernel*, *openshift*3.7*, puppet*

  # YUM module currently do not support --disableexcludes
  - name: Install Kernel packages to version {{ kernelversion }}
    command: yum install kernel-{{ kernelversion }} kernel-devel-{{ kernelversion }} kernel-tools-{{ kernelversion }} kernel-tools-libs-{{ kernelversion }} --disableexcludes=main -y
    args:
      warn: false
