---
- hosts: new_nodes

  tasks:
  - name: install the latest version of OS PreReq packages
    yum: pkg={{item}} state=present update_cache=yes
    with_items:
     - wget
     - git
     - net-tools
     - bind-utils
     - iptables-services
     - bridge-utils
     - bash-completion
     - kexec-tools
     - sos
     - psacct
     - NetworkManager
     - docker
     - atomic-openshift-excluder
     - atomic-openshift-docker-excluder
     - kernel-devel
    tags:
      - packages


  - name: Extending Logical Volume in masters
    lvol:
      vg: VolGroup00
      lv: LogVol02
      size: 40g
    tags:
      - lvm

  - name: Extending Filesystem
    filesystem:
      fstype: xfs
      dev: /dev/VolGroup00/LogVol02
      resizefs: yes
    tags:
      - lvm
#  - name: install the latest version of OpenShift PreReq packages
#    yum: pkg={{item}} state=present
#    with_items:

#  - name: Remove atomic-openshift packages from the exclude list '/etc/yum.conf'
#    command: atomic-openshift-excluder unexclude

#  - name: Upgrade all packages
#    yum: name='*' state=latest

  - name: hardened openshift - disable swap
    command: swapoff -a
    tags:
      - swap

  - name: make sure SELinux is enabled
    selinux:
      policy: targeted
      state: enforcing
    notify:
      - Reboot server
      - Reboot server wait
    tags:
      - selinux

  - service:
      name: docker
      state: stopped
    notify:
      - Reboot server
      - Reboot server wait

  - name: remove docker /var/lib fs
    file: path='/var/lib/docker'
    state: absent
    tags:
      - docker_cleanup

  - systemd:
      name: docker
      state: stopped
    tags:
      - docker_cleanup

  - name: Docker storage reset
    command: docker-storage-setup --reset
    tags:
      - docker_cleanup

  - name: Updating docker file '/etc/sysconfig/docker'
    lineinfile:
      path: /etc/sysconfig/docker
      regexp: '^OPTIONS='
      line: 'OPTIONS="--selinux-enabled --insecure-registry 172.32.0.0/16"'
    tags:
      - docker

  - name: Enable Docker Storage if not configured
    shell: grep -q ^DOCKER_STORAGE_OPTIONS.*thinpooldev /etc/sysconfig/docker-storage || docker-storage-setup
    args:
      executable: /bin/bash
    tags:
      - docker

  - name: Start and enable Docker service
    service:
      name: docker
      state: started
      enabled: yes
    tags:
      - docker

  - name: Start and enable NetworkManager service
    service:
      name: NetworkManager
      state: started
      enabled: yes

  handlers:
  - name: Reboot server
    command: /usr/bin/systemd-run --on-active=5 /usr/bin/systemctl reboot
    async: 0
    poll: 0

  - name: Reboot server wait
    local_action:
      wait_for
        host={{ inventory_hostname }}
        port=22
        delay=60
        timeout=300
