---
- hosts: nodes
  tasks:
  - name: remove the pkgs
    yum: pkg={{item}} state=absent
    with_items:
     - atomic-openshift-excluder
     - atomic-openshift-docker-excluder
     - atomic-openshift-clients
     - atomic-openshift-utils
     - atomic-openshift
