---
- hosts: nodes
  serial: 1
  tasks:
  - name: run register_satellite
    shell: wget --no-check-certificate https://pdl24vifsat01.ca.xxxxxx.com/pub/register_satellite.sh -O /root/register_satellite.sh ; chmod 775 /root/register_satellite.sh ; sh /root/register_satellite.sh
    args:
      executable: /bin/bash
