---
#Global "Attachment for all Patch Change Request"
# Non-Database Patch SOP Playbook
cr_attachment: "SOPStandardPatchingPlaybook.xlsx"

# Database Patch SOP Playbook
#cr_attachment: "SOPStandardPatchingPlaybookDatabase.xlsx"

custom_patch:
- affected_cis: "DRL02GGMAP01D,DRL02FBHAP003,DRL02BHTAP001,DRL02AS3AP005,DRL02AS3AP003,DRL02BHTWB002,DRL02GGMWB02D,DRL02FBHWB001,DRL02GGMWB03D,DRL02AS3AP004,DRL02GGMWB01D,DRL02GGMWB04D,DRL02KP9AP001,DRL02FBHAP001,DRL02FBHWB003,DRL02AS3AP002,DRL02GGMAP02D,DRL02BHTWB001,DRL02AS3AP001,DRL02GGMAP03D,DRL02GGMAP04D,Maestro (Batch)"
  short_description: "FY19 R1  OS Security Patching on OIG/vendor directory DR servers Total 21"
  planned_start_date: "2018-04-27 00:00:01"
  planned_duration: "1 1:00:00"
  outage_duration: "1 1:00:001"
  outage_starts: "2018-04-27 00:10:01"
  outage_systems_impacted: "Oracle Identity Governance (OIG),Vendor Directory,Vendor Oracle Identity Manager"
  outage_audience: "Archimedes (ARC)"
  ctasks:
    - assignment_group: "L1-MEM-IT-GLB"
    - assignment_group: "L2-APPTALK-IT-GLB"
    - assignment_group: "L2-DATACENTER-OPS-IT-GLB"
    - assignment_group: "L2-IAM-OIM-OPS-IT-US"
    - assignment_group: "L2-MW-APP-IT-GLB"
    - assignment_group: "L2-MW-MSG-IT-GLB"
    - assignment_group: "L2-PLT-LINUX-IT-US"
    - assignment_group: "L2-PLT-WINTEL-IT-US"
    - assignment_group: "L2-STORAGE-IT-US"
    - assignment_group: "L2-VIAM-OAM-OPS-IT-US"
    - assignment_group: "L2-VIAM-PING-OPS-IT-US"
    - assignment_group: "L3-VIAM-OUD-DEV-IT-US"

- affected_cis: "PDL01OMSAP01C,PDL01OMSAP04C,PDL01OMSAP05C,PDL01OMSMQ004,PDL01OMSWB01A,PDL01OMSAP07A,PDL01OMSAT07A,PDL01OMSWB03A,PDL01OMSAT14C,PDL01OMSAP06A,PDL01OMSAT04A,PDL01OMSAT03C,PDL01OMSMQ003,PDL01OMSMQ001,PDL01OMSAP04A,PDL01OMSAT05A,PDL01OMSAT14A,PDL01OMSAT05C,PDL01OMSAT12A,PDL01OMSAT08A,PDL01OMSAT10C,PDL01OMSWB02A,PDL01OMSAP02A,PDL01OMSAP12A,PDL01ARCAP001,PDL01OMSAT06A,PDL01OMSAT06C,PDL01OMSDB003,PDL01OMSAT02A,PDL01OMSAT12C,PDL01OMSAP03C,PDL01OMSAT08C,PDL01OMSDB003\\OP01EODB01,PDL01OMSAT01A,PDL01OMSDB003\\OP01AMDB01,PDL01OMSAP01A,PDL01OMSAP02C,PDL01OMSAT01C,PDL01OMSAP03A,PDL01ARCWB001,PDL01OMSAP001,PDL01OMSAT10A,PDL01OMSAP08C,PDL01OMSAT13C,PDL01OMSAP06C,PDL01D20UT01C,PDL01OMSAT09A,PDL01OMSAT07C,PDL01OMSAT13A,PDL01OMSAT04C,PDL01OMSAP07C,PDL01OMSAT02C,PDL01OMSAP08A,PDL01OMSAT03A,PDL01ARCAP01A,PDL01OMSAP05A,PDL01OMSAT09C,PDL01OMSAP12C,Retek Merchandising System (RMS)"
  short_description: "FY19 R3 patching on PD OMS Total 56 servers "
  planned_start_date: "2018-04-28 00:00:01"
  planned_duration: "1 1:00:00"
  outage_duration: "1 1:00:001"
  outage_starts: "2018-04-28 00:10:01"
  outage_systems_impacted: "Order Management System (OMS)"
  outage_audience: "OMS"
  ctasks:
    - assignment_group: "L1-MEM-IT-GLB"
    - assignment_group: "L2-ASM-OMS-IT-US"
    - assignment_group: "L2-DATACENTER-OPS-IT-GLB"
    - assignment_group: "L2-CASSANDRA-IT-US"
    - assignment_group: "L2-DB-ORACLE-IT-US"
    - assignment_group: "L2-MW-APP-IT-GLB"
    - assignment_group: "L2-MW-MSG-IT-GLB"
    - assignment_group: "L2-PLT-UNIX-IT-US"
    - assignment_group: "L2-PLT-WINTEL-IT-US"
    - assignment_group: "L2-STORAGE-IT-US"
    - assignment_group: "L2-APPTALK-IT-GLB"
    - assignment_group: "L2-TWS-IT-US"

