
   - name: Disable 3.6 subscription and enable 3.7
     shell: subscription-manager repos --disable="rhel-7-server-ose-3.6-rpms" --enable="rhel-7-server-ose-3.7-rpms" --enable="rhel-7-server-extras-rpms" --enable="rhel-7-fast-datapath-rpms"
     args:
       executable: /bin/bash
     tags:
       - subscribe

   - name: Upgrade the Packages
     yum: pkg={{item}} state=latest update_cache=yes
     with_items:
       - atomic-openshift-utils
       - atomic-openshift-excluder
       - atomic-openshift-docker-excluder
     tags:
       - upgrade

   - name: Deploy Docker 1.12.x
     yum: pkg={{item}} state=present allow_downgrade=yes update_cache=yes
     with_items:
       - docker-1.12.6
       - docker-client-1.12.6
       - docker-common-1.12.6
       - docker-rhel-push-plugin-1.12.6
     tags:
       - docker112

   - file:
     path: /usr/share/openshift/examples
     state: directory
     mode: 0755
     tags:
       - mkdir

   - copy:
       src: /usr/share/ansible/openshift-ansible/roles/openshift_examples/files/examples/v3.6/
       dest: /usr/share/openshift/examples/
       owner: root
       group: root
       mode: 0755
       remote_src: yes
     tags:
       - copy
