apiVersion: v1
kind: ReplicationController
metadata:
  name: egress_multi_rc_1
spec:
  replicas: 1
  selector:
    name: egress_multi_1
  template:
    metadata:
      name: egress_multi_1
      labels:
        name: egress_multi_1
      annotations:
        pod.network.openshift.io/assign-macvlan: "true"         
    spec:
      initContainers:
      - name: egress-router
        image: registry.access.redhat.com/openshift3/ose-egress-router
        securityContext:
          privileged: true
        env:
        - name: EGRESS_SOURCE
          value: 172.21.73.32
        - name: EGRESS_GATEWAY
          value: 172.21.73.1
        - name: EGRESS_DESTINATION
          valueFrom:
          configMapKeyRef:
          name: egress_routes_1
          key: destination
        - name: EGRESS_ROUTER_MODE
          value: init   
      containers:
      - name: egress-router-wait
        image: registry.access.redhat.com/openshift3/ose-pod
      nodeSelector:
        site: egress-ecomm-orderfraudservice
