apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: egress-svc-ecomm-rmq-pd
spec:
  ports:
  - name: egress-svc-ecomm-rmq-pd
    port: 5671
    protocol: TCP
    targetPort: 5671
  selector:
    name: egress-multi-1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
