apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: egress-svc-bbyca-resourceservice-corp
spec:
  ports:
  - name: egress-svc-bbyca-resourceservice-corp
    port: 443
  selector:
    name: egress-multi-2
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
