apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: egress-svc-mccp-il-webservices-hdc
spec:
  ports:
  - name: egress-svc-mccp-il-webservices-hdc
    port: 19012
    protocol: TCP
    targetPort: 19012
  selector:
    name: egress-multi-1
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
