apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: egress-svc-db
spec:
  ports:
  - name: egress-svc-db
    port: 50000
    protocol: TCP
    targetPort: 50000
  selector:
    name: egress-db
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
