---

- hosts: all
  become: true
  become_method: sudo
  gather_facts: false

  vars_prompt:
  - name: vg
    prompt: enter volume group name; e.g. docker_vg
    
  roles:
    - { role: ../roles/role_reshifter_etcd }
  
